# Generated by Django 4.2 on 2023-05-04 09:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('faciliti', '0001_initial'),
        ('apartment', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Апартаменты', 'verbose_name_plural': 'Апартаменты'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='apartment',
            name='during_stay',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='faciliti',
            field=models.ManyToManyField(null=True, related_name='apartments', to='faciliti.faciliti'),
        ),
    ]
