# Generated by Django 4.2 on 2023-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faciliti', '0001_initial'),
        ('apartment', '0003_alter_apartment_options_apartment_faciliti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='faciliti',
        ),
        migrations.AddField(
            model_name='apartment',
            name='faciliti',
            field=models.ManyToManyField(null=True, related_name='apartments', to='faciliti.faciliti'),
        ),
    ]
