# Generated by Django 4.2 on 2023-05-03 07:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_apartment_faciliti_apartment_faciliti'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='apartment',
            name='during_stay',
            field=models.TextField(blank=True),
        ),
    ]
