# Generated by Django 4.2 on 2023-05-04 11:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_apartment_contact_apartment_during_stay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
